name: Update DexScreener API Data

on:
  schedule:
    - cron: "*/1 * * * *"   # Runs every minute
  workflow_dispatch:        # Allows manual trigger

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch API Data
        run: |
          curl -s "https://api.dexscreener.com/latest/dex/tokens/0xA04BC7140c26fc9BB1F36B1A604C7A5a88fb0E70" -o unixtimestamp.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add unixtimestamp.json
          git commit -m "Update unixtimestamp.json [Automated]" || echo "No changes to commit"
          git push
